[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[context.production.environment]
  VITE_SUPABASE_URL = "YOUR_SUPABASE_URL"
  VITE_SUPABASE_ANON_KEY = "YOUR_SUPABASE_ANON_KEY"

[context.deploy-preview.environment]
  VITE_SUPABASE_URL = "YOUR_SUPABASE_URL"
  VITE_SUPABASE_ANON_KEY = "YOUR_SUPABASE_ANON_KEY"

[context.branch-deploy.environment]
  VITE_SUPABASE_URL = "YOUR_SUPABASE_URL"
  VITE_SUPABASE_ANON_KEY = "YOUR_SUPABASE_ANON_KEY"